syntax = "proto3";

package collector;

import "google/protobuf/timestamp.proto";

option go_package = "distributed-system-v2/proto/collector;collector";

message RepositoryRequest {
  string owner = 1;
  string repository_name = 2;
}

message RepositoryOwner { 
  string name = 1; 
}

message RepositoryResponse {
  RepositoryOwner owner = 1;
  string name = 2;
  string description = 3;
  int32 stargazers_count = 4;
  int32 forks_count = 5;
  google.protobuf.Timestamp creation_date = 6;
}

service CollectorService {
  rpc GetRepositoryInformation(RepositoryRequest) returns (RepositoryResponse);
}